import { PeriodicElement, Sort } from "../models/Appointment.models";

export const ELEMENT_DATA: PeriodicElement[] = [
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
  {
    flow: "l",
    type: "DI",
    book: "FAO..",
    container: "REAS..",
    iso: "22G1",
    line: "COS",
    info: "--",
    expiry: "29/08/2020",
    hold: "--",
    trip: 477312,
    selected: false,
  },
];

export const sorts: Sort[] = [
  { value: "Sort", viewValue: "Sort" },
  { value: "Sort-1", viewValue: "Sort 1" },
  { value: "Sort-2", viewValue: "Sort 2" },
];

export const displayedColumns: string[] = [
  "select",
  "flow",
  "type",
  "book",
  "container",
  "iso",
  "line",
  "info",
  "expiry",
  "hold",
  "trip",
];
